"""redo

Revision ID: f39206cf4c78
Revises: 
Create Date: 2021-10-24 12:20:33.640448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39206cf4c78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=2048), nullable=True),
    sa.Column('htmlpath', sa.String(length=2048), nullable=True),
    sa.Column('filename', sa.String(length=2048), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_location_filename'), 'image_location', ['filename'], unique=False)
    op.create_index(op.f('ix_image_location_htmlpath'), 'image_location', ['htmlpath'], unique=False)
    op.create_index(op.f('ix_image_location_location'), 'image_location', ['location'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_image_location_location'), table_name='image_location')
    op.drop_index(op.f('ix_image_location_htmlpath'), table_name='image_location')
    op.drop_index(op.f('ix_image_location_filename'), table_name='image_location')
    op.drop_table('image_location')
    # ### end Alembic commands ###
